library("airway")
library("tximeta")
library("magrittr")
library("DESeq2")
library("AnnotationDbi")
#library("org.Hs.eg.db")  # ----> HUMAN
#columns(org.Hs.eg.db)   # ---->  HUMAN
library("org.Mm.eg.db") # --Mouse
columns(org.Mm.eg.db)  # -- Mouse
#NOTE: IN HUMAN 1, 15 are working, in MOUSE 1, 18 rownames length should be given.


csvfile <- file.path("SPF_fast_fed.csv")
coldata <- read.csv(csvfile, row.names=1, stringsAsFactors=FALSE)
coldata
dir  <- "provide the path of transcript count generated by salmon.sh pipelines"
coldata$files <- file.path(dir,"quants", coldata$name, "quant.sf")
coldata
file.exists(coldata$files)
se <- tximeta(coldata)
dim(se)
head(rownames(se))
gse <- summarizeToGene(se)
dim(gse)
head(rownames(gse))
gse
assayNames(gse)
head(assay(gse), 3)
colSums(assay(gse))
rowRanges(gse)
seqinfo(rowRanges(gse))
colData(gse)
gse$names %<>% factor
gse$donor %<>% factor
gse$condition %<>% factor
colData(gse)
gse$donor
gse$condition
levels(gse$condition)
countdata <- round(assays(gse)[["counts"]])
head(countdata, 3)
write.table(countdata, file="count_matrix_control_case.csv", sep=",", row.names=TRUE)
coldata <- colData(gse)
rownames(coldata)
colnames(countdata)
ddsMat <- DESeqDataSetFromMatrix(countData = countdata, colData = coldata, design = ~ condition)
nrow(ddsMat)
keep <- rowSums(counts(ddsMat)) > 1
ddsMat <- ddsMat[keep,]
nrow(ddsMat)
ddsMat <- DESeq(ddsMat)
res <- results(ddsMat, contrast=c("condition","A_control", "B_case"))
res <- res[order(res$pvalue),]
res
summary(res)
mcols(res, use.names = TRUE)
write.table(res, file="SPF_fast_fed_result_RNA.csv", sep=",", row.names=TRUE)
ens.str <- substr(rownames(res), 1, 18)
res$symbol <- mapIds(org.Mm.eg.db, keys=ens.str, column="SYMBOL", keytype="ENSEMBL", multiVals="first")
res$entrez <- mapIds(org.Mm.eg.db, keys=ens.str, column="ENTREZID", keytype="ENSEMBL", multiVals="first")
resOrdered <- res[order(res$pvalue),]
head(resOrdered)
resOrderedDF <- as.data.frame(resOrdered)
write.csv(resOrderedDF, file = "SPF_fast_fed_With_annotation_result_RNA.csv")
